### ISSUE TITLE
jBox.all.min.js:2 Uncaught TypeError: el.css is not a function - Conflict with nanogallery2

### ISSUE THREAD

**Issue by wobility** [StephanWagner/jBox#161]
Good morning all,

Could you help me solve a problem? I am using the awesome Jbox script and I have a conflict issue with nanogallery2 which I am also using on the same page. If I remove nanogallery2 Jbox notice is displayed correctly. On the other hand if I load it I have an error.

> new jBox('Notice', { content: 'Test', color: 'red'});
jBox.all.min.js:2 Uncaught TypeError: el.css is not a function
    at a._onPosition (jBox.all.min.js:2)
    at a._fireEvent (jBox.all.min.js:2)
    at a.position (jBox.all.min.js:2)
    at a.<anonymous> (jBox.all.min.js:2)
    at a.open (jBox.all.min.js:2)
    at a._onInit (jBox.all.min.js:2)
    at a._fireEvent (jBox.all.min.js:2)
    at new a (jBox.all.min.js:2)
    at <anonymous>:1:1
_onPosition @ jBox.all.min.js:2
_fireEvent @ jBox.all.min.js:2
a.position @ jBox.all.min.js:2
(anonymous) @ jBox.all.min.js:2
a.open @ jBox.all.min.js:2
_onInit @ jBox.all.min.js:2
_fireEvent @ jBox.all.min.js:2
a @ jBox.all.min.js:2
(anonymous) @ VM3521:1

**Comment by StephanWagner** [comment]
Could you check with jBox version 1.2.2? Should be fixed in this version.

**Comment by wobility** [comment]
> Could you check with jBox version 1.2.2? Should be fixed in this version.

I will give it a try. Thank you for your quick answer !

**Comment by wobility** [comment]
> Could you check with jBox version 1.2.2? Should be fixed in this version.

I no longer have the error that is displayed now, but the alert still does not appear ...  I use this call in Js console on google chrome for my test. When I try to call this code below it's ok on all my page except on page with nanogallery2.

> new jBox('Notice', { content: 'TEST', color: 'red', delayOpen:500, autoClose: 45000, delayClose: 45000, fade : 400, animation: {open: 'pulse', close: 'zoomIn'}, closeButton: true, showCountdown: true, position:{x: 15, y: 15}});

**Comment by StephanWagner** [comment]
That's the fiddle I used for debugging. Seems to work just fine: https://jsfiddle.net/StephanWagner/8267jmLc/

Maybe it's a z-index issue? jBox uses by default 10000, can be adjusted with option `zindex` though.

**Comment by wobility** [comment]
it's working ! thanks a lot.
