### ISSUE TITLE
Draggable not working on touch devices

### ISSUE THREAD

**Issue by anzeznidarsic** [StephanWagner/jBox#18]
Draggable examples are not working on touch devices (tested on iOS 8)

**Comment by vhornik** [comment]
Hi Stephan, jBox is great, but the touch support is really missing... any update on this?
Maybe it's not so difficult, I found this for example: http://grantm.github.io/jquery-udraggable/  seems pretty lightweight, could be combined somehow?

**Comment by StephanWagner** [comment]
Finally supported with version v0.8.0

**Comment by manukieli** [comment]
Hi, very good script, but I need ti use it for mobile devices and it doesn't work to.
I've try the version 1.0.6

**Comment by StephanWagner** [comment]
@manukieli With what device are you testing? I just tried it with iPhone and it did work.

**Comment by manukieli** [comment]
I've try it from my Samsung S8 with chrome and from computer with Chrome and active the option of mobile device, both doesn't work
![drag_from_mobile](https://user-images.githubusercontent.com/14294794/69884374-67af5080-12d8-11ea-80f4-eea4a8bee90b.gif)

**Comment by StephanWagner** [comment]
It does work on Chrome iPhone too. Unfortunately, I  don't have an Android phone right now, but I'm reopening this issue. It can be reproduced when using the Crome dev tools.

**Comment by Developer66** [comment]
Scroll and Drag not working on Android mobile devices. Is there anything new on this issue?

Testet on S8+, Tab 10 in Chrome and Samsung Browser

Thanks

**Comment by StephanWagner** [comment]
Just released v1.2.9 with some improvements that should fix draggable on mobile devices.

**Comment by StephanWagner** [comment]
Actually use v1.2.10 or 1.2.11 as I published v1.2.9 wrongly

**Comment by StephanWagner** [comment]
I also fixed an issue that prevented the jBox from closing on mobile devices when dragging was set to title. Use from version v1.2.13. Tested on Chrome debugging tools and iPhone.

**Comment by Developer66** [comment]
Thanks for your work! Works now perfectly for Android mobile devices.

Some Problem still exist:
When Drag is enabled, the scroll is not working on mobile devices. Maybe it would be better to put the dragevent only on the titlebar?

Thanks

**Comment by StephanWagner** [comment]
Do you mean scrolling within the jBox or page scrolling?

You can set the option `draggable`  to `title`, then only the title bar let's you drag the jBox. You could also pass a jQuery element that will trigger dragging. `true` will set the whole jBox to the draggable handler: https://stephanwagner.me/jBox/options#other-options

**Comment by Developer66** [comment]
I mean the scrolling in the jbox content.

With the option `title` it works perfect... I set `draggable: true`, but then the whole popup is draggable... with `draggable: 'title',` it is only the title... Thanks a lot
